# Generated by Django 6.0.3 on 2026-05-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wallet_creditledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyprofile',
            name='first_time_import_customers',
            field=models.BooleanField(default=False),
        ),
    ]
