# Generated by Django 6.0.3 on 2026-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shopifyprofile_first_time_import_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyprofile',
            name='connect_products',
            field=models.BooleanField(default=False),
        ),
    ]