# Generated by Django 6.0.3 on 2026-04-14 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('subscribed', 'Subscribed'), ('opted_out', 'Opted Out'), ('bounced', 'Bounced'), ('blocked', 'Blocked')], default='subscribed', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('shopify', 'Shopify'), ('api', 'API'), ('keyword', 'Keyword Opt-In')], default='manual', max_length=20)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('custom_attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.contactlist')),
            ],
            options={
                'indexes': [models.Index(fields=['phone'], name='contacts_co_phone_5a60c7_idx'), models.Index(fields=['contact_list', 'status'], name='contacts_co_contact_9aa996_idx'), models.Index(fields=['contact_list', 'created_at'], name='contacts_co_contact_40a142_idx')],
                'unique_together': {('contact_list', 'phone')},
            },
        ),
    ]
