# Generated by Django 6.0.3 on 2026-05-04 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_contact_9aa996_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_contact_40a142_idx',
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contact',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['users', 'status'], name='contacts_co_users_i_239cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['users', 'created_at'], name='contacts_co_users_i_b84131_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('users', 'phone'), name='unique_contact_phone_per_user'),
        ),
        migrations.AddField(
            model_name='segmentmembership',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_memberships', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='segmentmembership',
            name='contact_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='contacts.contactlist'),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_list',
        ),
        migrations.AddIndex(
            model_name='segmentmembership',
            index=models.Index(fields=['contact_list'], name='contacts_se_contact_98e105_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentmembership',
            index=models.Index(fields=['contact'], name='contacts_se_contact_dd2f77_idx'),
        ),
        migrations.AddConstraint(
            model_name='segmentmembership',
            constraint=models.UniqueConstraint(fields=('contact_list', 'contact'), name='unique_contact_per_segment'),
        ),
    ]
