# Generated by assistant — add idempotency_key to Content
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='idempotency_key',
            field=models.CharField(max_length=64, null=True, blank=True, unique=True, db_index=True),
        ),
    ]
