# Generated by Django 6.0.3 on 2026-05-04 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_wallet_creditledger'),
        ('contacts', '0003_segmentmembership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyCustomerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_customer_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('phone_snapshot', models.CharField(blank=True, max_length=20)),
                ('marketing_state', models.CharField(blank=True, max_length=32)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_links', to='contacts.contact')),
                ('shopify_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_links', to='accounts.shopifyprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['shopify_profile', 'shopify_customer_id'], name='shopify_sho_shopify_318113_idx'), models.Index(fields=['contact'], name='shopify_sho_contact_90fcc4_idx'), models.Index(fields=['email_snapshot'], name='shopify_sho_email_s_d36ca4_idx'), models.Index(fields=['phone_snapshot'], name='shopify_sho_phone_s_01d65e_idx')],
                'constraints': [models.UniqueConstraint(fields=('shopify_profile', 'shopify_customer_id'), name='unique_shopify_customer_per_shop')],
            },
        ),
    ]
