# Generated by Django 6.0.3 on 2026-05-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_remove_shopify_customer_email_storage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shopifycustomerlink',
            name='shopify_sho_email_s_d36ca4_idx',
        ),
        migrations.AddField(
            model_name='shopifycustomerlink',
            name='email_snapshot',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
