# Generated by Django 6.0.3 on 2026-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shopifyprofile_first_time_import_customers'),
        ('shopify', '0003_remove_shopifycustomerlink_shopify_sho_email_s_d36ca4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_product_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('handle', models.CharField(blank=True, max_length=255)),
                ('description_html', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('featured_image_url', models.URLField(blank=True, max_length=2048)),
                ('total_inventory', models.IntegerField(blank=True, null=True)),
                ('has_out_of_stock_variants', models.BooleanField(default=False)),
                ('is_gift_card', models.BooleanField(default=False)),
                ('variant_count', models.PositiveIntegerField(default=0)),
                ('media_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('shopify_created_at', models.DateTimeField(blank=True, null=True)),
                ('shopify_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_profile', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='products', to='accounts.shopifyprofile')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['shopify_profile', 'deleted_at'], name='shop_prod_shop_del_idx'),
                    models.Index(fields=['shopify_profile', 'shopify_updated_at'], name='shop_prod_shop_upd_idx'),
                    models.Index(fields=['shopify_profile', 'handle'], name='shop_prod_shop_handle_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('shopify_profile', 'shopify_product_id'), name='unique_shopify_product_per_shop'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ShopifyProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_media_id', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('external_video', 'External Video'), ('model_3d', '3D Model'), ('unknown', 'Unknown')], default='image', max_length=32)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('preview_image_url', models.URLField(blank=True, max_length=2048)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='media', to='shopify.shopifyproduct')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['product', 'media_type'], name='shop_media_prod_type_idx'),
                    models.Index(fields=['product', 'deleted_at'], name='shop_media_prod_del_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('product', 'shopify_media_id'), name='unique_shopify_media_per_product'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ShopifyProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_variant_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('inventory_quantity', models.IntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('shopify_image_id', models.CharField(blank=True, max_length=255)),
                ('featured_image_url', models.URLField(blank=True, max_length=2048)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='variants', to='shopify.shopifyproduct')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['product', 'deleted_at'], name='shop_var_prod_del_idx'),
                    models.Index(fields=['sku'], name='shop_var_sku_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('product', 'shopify_variant_id'), name='unique_shopify_variant_per_product'),
                ],
            },
        ),
    ]