# Generated by Django 6.0.3 on 2026-05-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_shopify_product_catalog_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shopifyproduct',
            new_name='shopify_sho_shopify_4c2b2a_idx',
            old_name='shop_prod_shop_del_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyproduct',
            new_name='shopify_sho_shopify_6377b5_idx',
            old_name='shop_prod_shop_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyproduct',
            new_name='shopify_sho_shopify_18554f_idx',
            old_name='shop_prod_shop_handle_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyproductmedia',
            new_name='shopify_sho_product_878092_idx',
            old_name='shop_media_prod_type_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyproductmedia',
            new_name='shopify_sho_product_900c06_idx',
            old_name='shop_media_prod_del_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyproductvariant',
            new_name='shopify_sho_product_36e0e5_idx',
            old_name='shop_var_prod_del_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyproductvariant',
            new_name='shopify_sho_sku_475ef6_idx',
            old_name='shop_var_sku_idx',
        ),
    ]
