# Generated by Django 6.0.3 on 2026-05-29 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('sms', '0004_qrcode_contact_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='sms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.sms'),
        ),
    ]
