# Generated by Django 6.0.3 on 2026-05-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_automation_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='sms',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
