# Generated by Django 6.0.3 on 2026-05-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_alter_automation_sms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automation',
            old_name='sms',
            new_name='sms_body',
        ),
        migrations.AlterField(
            model_name='automation',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
