# Generated by Django 6.0.3 on 2026-05-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_rename_sms_automation_sms_body_alter_automation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='sms_sender',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
