# Generated by Django 6.0.3 on 2026-05-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_automation_sms_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='segment_list_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
