# Generated by Django 6.0.3 on 2026-05-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_automation_segment_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('activated', 'Activated'), ('deactivated', 'Deactivated')], default='created'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='automation_type',
            field=models.CharField(choices=[('welcome_user', 'Welcome sms'), ('recurring', 'Recurring sms')], max_length=50),
        ),
    ]
