# Generated by Django 6.0.3 on 2026-05-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_automation_status_alter_automation_automation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='task_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
