# Generated by Django 6.0.3 on 2026-05-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_automation_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='every',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='automation',
            name='period',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
