# Generated by Django 6.0.3 on 2026-04-23 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
        ('contacts', '0002_contact'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(max_length=32, unique=True)),
                ('sender', models.CharField(max_length=20)),
                ('body', models.TextField(max_length=1600)),
                ('rendered_content_snapshot', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('sent', 'Sent'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_campaign_id', models.CharField(blank=True, max_length=255)),
                ('has_cta_links', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='campaign.campaign')),
                ('contact_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='contacts.contactlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmsPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_slug', models.SlugField(max_length=64, unique=True)),
                ('page_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('content_snapshot', models.JSONField()),
                ('snapshot_version', models.PositiveIntegerField(default=1)),
                ('requires_token', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sms', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='sms.sms')),
                ('source_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_pages', to='content.content')),
            ],
        ),
        migrations.CreateModel(
            name='SmsPageAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=120)),
                ('action_type', models.CharField(choices=[('url', 'URL'), ('deep_link', 'Deep Link'), ('phone', 'Phone'), ('email', 'Email'), ('download', 'Download'), ('form_submit', 'Form Submit'), ('video', 'Video'), ('custom', 'Custom')], max_length=30)),
                ('target_url', models.URLField(blank=True, max_length=500)),
                ('target_value', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='sms.smspage')),
            ],
            options={
                'unique_together': {('page', 'action_key')},
            },
        ),
        migrations.CreateModel(
            name='SmsRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('access_token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('undelivered', 'Undelivered'), ('opted_out', 'Opted Out')], default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('provider_status', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('page_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_recipients', to='contacts.contact')),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='sms.sms')),
            ],
        ),
        migrations.CreateModel(
            name='SmsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('page_view', 'Page View'), ('video_play', 'Video Play'), ('video_complete', 'Video Complete'), ('cta_click', 'CTA Click'), ('form_submit', 'Form Submit'), ('opt_out', 'Opt Out')], max_length=30)),
                ('component_key', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sms.sms')),
                ('page_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='sms.smspageaction')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sms.smsrecipient')),
            ],
        ),
    ]
