# Generated by Django 6.0.3 on 2026-05-21 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_segmentmembership_and_more'),
        ('sms', '0003_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='contact_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='contacts.contactlist'),
        ),
    ]
