# Generated by Django 6.0.3 on 2026-05-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_qrcode_contact_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('automated', 'Automated'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('sent', 'Sent'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
