# Generated by Django 6.0.3 on 2026-05-11 19:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_shopifyprofile_connect_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantBillingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_public_name', models.CharField(blank=True, max_length=100)),
                ('partner_development', models.BooleanField(default=False)),
                ('shopify_plus', models.BooleanField(default=False)),
                ('is_billable', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_shop_snapshot', models.JSONField(blank=True, default=dict)),
                ('merchant_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_state', to='accounts.shopifyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SmsPackage',
            fields=[
                ('package_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sms_count', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_packages', to='accounts.shopifyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('shopify', 'Shopify')], default='shopify', max_length=20)),
                ('purchase_kind', models.CharField(choices=[('one_time', 'One Time')], default='one_time', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('settled', 'Settled'), ('declined', 'Declined'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('provider_charge_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('confirmation_url', models.URLField(blank=True, max_length=1000)),
                ('return_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('price_snapshot', models.JSONField(blank=True, default=dict)),
                ('credits_snapshot', models.JSONField(blank=True, default=dict)),
                ('plan_snapshot', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='payment.smspackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('shop_domain', models.CharField(max_length=255)),
                ('external_event_id', models.CharField(blank=True, max_length=255)),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['topic', 'shop_domain'], name='payment_web_topic_84e166_idx'), models.Index(fields=['processed_at'], name='payment_web_process_92b4bd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_event_id', ''), _negated=True), fields=('topic', 'shop_domain', 'external_event_id'), name='payment_unique_webhook_external_event')],
            },
        ),
    ]
